stages:
  - test
  - build
  - deploy

linting:
  stage: test
  image: node:16-alpine
  script:
    - yarn install && yarn lint
  only:
    - develop
    - /^release\/v[0-9]+\.[0-9]+\.[0-9]+$/

build:
  stage: build
  image: node:16-alpine
  script:
    - yarn install && yarn build
  artifacts:
    paths:
      - dist
    expire_in: 20min
  only:
    - develop
    - /^release\/v[0-9]+\.[0-9]+\.[0-9]+$/

deploy (develop):
  stage: deploy
  image: alpine
  before_script:
    - apk add openssh-client && apk add bash
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY_DEV" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
  script:
    - bash deploy/deploy.sh $DEPLOY_SERVER_DEV $DOPPLER_SERVICE_TOKEN_DEV $CI_COMMIT_REF_NAME $WORKING_DIRECTORY_DEV
  only:
    - develop

deploy (qa):
  stage: deploy
  image: alpine
  before_script:
    - apk add openssh-client && apk add bash
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY_QA" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
  script:
    - bash deploy/deploy.sh $DEPLOY_SERVER_QA $DOPPLER_SERVICE_TOKEN_QA $CI_COMMIT_REF_NAME $WORKING_DIRECTORY_QA
  only:
    - /^release\/v[0-9]+\.[0-9]+\.[0-9]+$/
